Updated help descriptions of the commands
canonical/greenhouse-automations pull request #50
Opened 2022-02-22 16:31 UTC by ilayda21

# Done
- Commands, arguments and options descriptions are updated.

# QA
- Checkout the feature branch
- Install dependencies with `yarn`
- Run `ts-node ./src/index.ts --help` 
- Verify the program description is correct.
- Verify the usage is correct.
- Verify the "add-posts" command's description is correct.
- Verify the "delete-posts" command's description is correct.
- Run `ts-node ./src/index.ts add-posts --help`
- Verify the command's description is correct
- Verify the argument and options descriptions are correct.
- Verify the usage is correct. 
- Run `ts-node ./src/index.ts delete-posts --help`
- Verify the command's description is correct
- Verify the argument and options descriptions are correct.
- Verify the usage is correct.

Fixes #48

2022-02-22 17:08 UTC, andesol approved these changes
LGTM!

Just some minor comments

2022-02-22 17:08 UTC, andesol commented on src/common/commandDescriptios.ts
> +export const ADD_POSTS_DESCRIPTION = "This command creates job posts for a specific job <job-id> in the specified regions <region-name> from all existing job posts in the Canonical Board. If the clon
This sentence sounds a bit repetitive to me:
"If the clone-from is specified, the command will create job posts in the specified regions from that job post"

Maybe something along the lines:
"If clone-from is specified, the new job post will be created based on the existing one"

(Can't come up with anything better right now)

2022-02-22 17:08 UTC, andesol commented on src/common/commandDescriptios.ts
> +export const JOB_ID_DESCRIPTION = "The job-id is the ID of a job that the user is a Hiring lead of. This ID can be found in the URL of the job page. If the user is not a hiring lead on the specified
It makes sense to lower case "hiring lead", IMHO

2022-02-22 17:08 UTC, andesol commented on src/index.ts
> +import { ADD_POSTS_DESCRIPTION, ADD_POSTS_REGIONS_DESCRIPTION, ADD_POSTS_USAGE, CLONE_FROM_DESCRIPTION, DELETE_POSTS_DESCRIPTION, DELETE_POSTS_REGIONS_DESCRIPTION, DELETE_POSTS_USAGE, GENERAL_DESCRIP
One little typo:

```suggestion
import { ADD_POSTS_DESCRIPTION, ADD_POSTS_REGIONS_DESCRIPTION, ADD_POSTS_USAGE, CLONE_FROM_DESCRIPTION, DELETE_POSTS_DESCRIPTION, DELETE_POSTS_REGIONS_DESCRIPTION, DELETE_POSTS_USAGE, GENERAL_DESCRIPTION, INTERACTIVE_DESCRIPTION, JOB_ID_DESCRIPTION, SIMILAR_DESCRIPTION } from "./common/commandDescriptions";
```

Alternatively you can do:
```
import * as commands from ...
```
As you prefer

2022-02-22 21:08 UTC, tbille requested changes
I just qa on the terminal, the text is super heavy :scream: 
I'll block the PR to have a chat with you if we can write down shorter summaries for the arguments.

2022-02-23 11:37 UTC, tbille commented
@ilayda21 why is the usage always showing "index", I am guessing it's the name of the file. When we build the snap will it show index too or will it show greenhouse?

2022-02-23 11:46 UTC, ilayda21 commented
@tbille no it will display "greenhouse" instead of "index"

2022-02-23 13:20 UTC, tbille approved these changes
Looks good!

2022-02-23 13:20 UTC, merged

2022-02-23 13:24 UTC, ilayda21 commented on src/index.ts
> +        throw Error(`No job post found in the Canonical board.`);
yes if its single line you dont have to put them